name = "Tim Howard"
license = "MIT"
licenselink = ""
description = "Tim Howard's notes, posts, and resume theme"
homepage = ""
tags = ["notes", "resume", "minimal", "personal"]
features = ["notes", "posts", "resume", "rss"]
min_version = "0.115.0"

[author]
  name = "Tim Howard"
  homepage = ""
